# EFC1 GCC253 - Complexidade e Projeto de Algoritmos - 5 pontos.


> **Prof.: Douglas H. S. Abreu**


**Aluno**: Felipe Carvalho Godoi

**Matricula**: 201920237

**Turma**: 10A, 14A

Link do repositório GitHub: 

● O trabalho deve ser feito em grupos de no máximo 4 componentes (Apenas um deve enviar a atividade no Campus Virtual)

● Trabalhos entregues após a data limite não serão aceitos

● Data limite de entrega: 20 de Novembro de 2022 : 23h55m

● Enviar o trabalho para o campus virtual, do seguinte modo: link do repositório GitHub com acesso ao Notebook.

● O trabalho deve ser desenvolvido no modelo Notebook utilizando preferencialmente a linguagem Python

# Importações e Variáveis globais

In [3]:
import numpy as np

global_1=0

def generateArray(size, min, max):
  arr = np.array(np.random.randint(min,max))
  for i in range(size):
      n1 = np.array(np.random.randint(min,max))
      arr = np.append(arr,n1)
  return arr

# Funções de Ordenação

> Utilize este espaço para definir as funções de ordenação.



##  Insertion Sort


In [4]:
def insertionSort(array):
  for i in range(1, len(array)):
    item = array[i]
    j = i - 1
    while j >= 0 and array[j] > item:
      array[j+1] = array[j]
      j -= 1
    array[j+1] = item
  return array

##  Merge Sort


In [10]:
def merge(array, begin, mid, end):
  sizeLeft = mid - begin + 1
  sizeRight = end - mid

  L = np.arange(sizeLeft)
  R = np.arange(sizeRight)

  for i in range(0, sizeLeft):
    L[i] = array[begin + i]
  for i in range(sizeRight):
    R[i] = array[mid + i + 1]

  i = 0
  j = 0
  k = begin

  while i < len(L) and j < len(R):
    if L[i] <= R[j]:
      array[k] = L[i]
      i += 1
    else:
      array[k] = R[j]
      j += 1
    k += 1
 
  while i < len(L):
    array[k] = L[i]
    i += 1
    k += 1

  while j < len(R):
    array[k] = R[j]
    j += 1
    k += 1

  return array

def mergeSort(array, begin, end):
  if begin < end:
    mid = int((begin + end) / 2)
    mergeSort(array, begin, mid)
    mergeSort(array, mid + 1, end)

    return merge(array, begin, mid, end)
  
  return array

##  Selection Sort


In [11]:
def selectionSort(array):
  for i in range(0, len(array) - 1):
    positionMin = i
    for j in range(i, len(array)):
      if array[j] < array[positionMin]:
        positionMin = j
    temp = array[i]
    array[i] = array[positionMin]
    array[positionMin] = temp
  return array

##  Bubble Sort


In [12]:
def bubbleSort(array):
  for i in range(len(array) - 1):
    for j in range(len(array) - i - 1):
      if array[j] > array[j + 1]:
        aux = array[j]
        array[j] = array[j + 1]
        array[j + 1] = aux
  return array

## Heap Sort

In [67]:
def heapify(array, i):
  size = len(array)
  l = 2 * i + 1
  r = 2 * i + 2

  larger = i
  if l < size and array[l] > array[larger]:
    larger = l
 
  if r < size and array[r] > array[larger]:
    larger = r
 
  if larger != i:
    array[i], array[larger] = array[larger], array[i]
    heapify(array, larger)


def heapSort(array):
  size = len(array)
  for i in range(int(size / 2) - 1, -1, -1):
    heapify(array, i)

  for i in range(size - 1, -1, -1):
    array[i], array[0] = array[0], array[i]
    heapify(array, 0)

  return array

## Quick Sort com pivo sendo o ultimo elemento do arranjo

> pivo = *A[A-comprimento]*

In [14]:
def partition(array, begin, end):
  pivo = array[end]
  i = begin - 1

  for j in range(begin, end):
    if array[j] <= pivo:
      i += 1
      array[i], array[j] = array[j], array[i]

  array[i + 1], array[end] = array[end], array[i + 1]
  return i + 1

def quickSort(array, begin, end):
  if begin < end:
    mid = partition(array, begin, end)
    quickSort(array, begin, mid - 1)
    quickSort(array, mid + 1, end)

  return array

# Questões



1.   Escolha pelo menos 3 arranjos. Ex: ***A[5,...,1000,...,100]*** e mostre o funcionamento dos Algoritmos realizando a ordenação.





In [6]:
array1 = generateArray(10, 0, 100)
array2 = generateArray(5, 0, 100)
array3 = generateArray(7, 0, 100)

print(array1)
print(array2)
print(array3)

[47 90 39 93 12 56 31 60 90 25 48]
[93 86 75 15  3 86]
[88 75 90 71 35 57 10 72]


## Insertion sort

In [7]:
copyArray1 = np.copy(array1)
copyArray2 = np.copy(array2)
copyArray3 = np.copy(array3)

print(insertionSort(copyArray1))
print(insertionSort(copyArray2))
print(insertionSort(copyArray3))

[12 25 31 39 47 48 56 60 90 90 93]
[ 3 15 75 86 86 93]
[10 35 57 71 72 75 88 90]


## Selection sort

In [70]:
copyArray1 = np.copy(array1)
copyArray2 = np.copy(array2)
copyArray3 = np.copy(array3)

print(selectionSort(copyArray1))
print(selectionSort(copyArray2))
print(selectionSort(copyArray3))

[ 3  9 32 34 37 38 38 42 60 65 74]
[29 39 49 57 68 87]
[ 9 34 42 50 73 91 93 95]


## Bubble sort

In [71]:
copyArray1 = np.copy(array1)
copyArray2 = np.copy(array2)
copyArray3 = np.copy(array3)

print(bubbleSort(copyArray1))
print(bubbleSort(copyArray2))
print(bubbleSort(copyArray3))

[ 3  9 32 34 37 38 38 42 60 65 74]
[29 39 49 57 68 87]
[ 9 34 42 50 73 91 93 95]


## Heap sort

In [72]:
copyArray1 = np.copy(array1)
copyArray2 = np.copy(array2)
copyArray3 = np.copy(array3)

print(heapSort(copyArray1))
print(heapSort(copyArray2))
print(heapSort(copyArray3))

[74 65 60 42 37 38 38  9  3 32 34]
[87 68 39 57 49 29]
[95 93 42 91 73 34  9 50]


## Merge sort

In [73]:
copyArray1 = np.copy(array1)
copyArray2 = np.copy(array2)
copyArray3 = np.copy(array3)

print(mergeSort(copyArray1, 0, len(copyArray1) - 1))
print(mergeSort(copyArray2, 0, len(copyArray2) - 1))
print(mergeSort(copyArray3, 0, len(copyArray3) - 1))

[ 3  9 32 34 37 38 38 42 60 65 74]
[29 39 49 57 68 87]
[ 9 34 42 50 73 91 93 95]


## Quick sort

In [74]:
copyArray1 = np.copy(array1)
copyArray2 = np.copy(array2)
copyArray3 = np.copy(array3)

print(quickSort(copyArray1, 0, len(copyArray1) - 1))
print(quickSort(copyArray2, 0, len(copyArray2) - 1))
print(quickSort(copyArray3, 0, len(copyArray3) - 1))

[ 3  9 32 34 37 38 38 42 60 65 74]
[29 39 49 57 68 87]
[ 9 34 42 50 73 91 93 95]
