# EFC1 GCC253 - Complexidade e Projeto de Algoritmos - 5 pontos.


> **Prof.: Douglas H. S. Abreu**


**Aluno**: </br>
Pedro Henrique dos Santos Mateus </br>

Felipe Carvalho Godoi

**Matricula**: </br>
201910948 </br>

201920237

**Turma**: 10A

Link do repositório GitHub: 

● O trabalho deve ser feito em grupos de no máximo 4 componentes (Apenas um deve enviar a atividade no Campus Virtual)

● Trabalhos entregues após a data limite não serão aceitos

● Data limite de entrega: 20 de Novembro de 2022 : 23h55m

● Enviar o trabalho para o campus virtual, do seguinte modo: link do repositório GitHub com acesso ao Notebook.

● O trabalho deve ser desenvolvido no modelo Notebook utilizando preferencialmente a linguagem Python

# Importações e Variáveis globais

In [19]:
import numpy as np

global_1=0

def generateArray(size, min, max):
  arr = np.array(np.random.randint(min,max))
  for i in range(size - 1):
      n1 = np.array(np.random.randint(min,max))
      arr = np.append(arr,n1)
  return arr

# Funções de Ordenação

> Utilize este espaço para definir as funções de ordenação.



##  Insertion Sort


In [2]:
def insertionSort(vetor):
  for j in range(1,len(vetor)):
    chave = vetor[j]
    i = j - 1
    while i >= 0 and vetor[i] > chave:
      vetor[i+1] = vetor[i]
      i = i - 1
    vetor[i+1] = chave
  return vetor

##  Merge Sort


In [80]:
def intercala(vetor,p,q,r):
  esquerda = np.copy(vetor[p:q])
  direita = np.copy(vetor[q:r])
  
  i,j = 0,0
  
  for k in range(p,r):
    if(i>=len(esquerda)):
      vetor[k] = direita[j]
      j = j+1
    elif(j>=len(direita)):
      vetor[k] = esquerda[i]
      i = i+1

    elif esquerda[i] < direita[j]:
      vetor[k] = esquerda[i]
      i = i+1
    else:
      vetor[k] = direita[j]
      j = j+1 

def mergeSort(vetor,p=0,r=None):
  if r is None:
    r = len(vetor)
  if (r - p) > 1:
    q = (p+r)//2
    mergeSort(vetor,p,q)
    mergeSort(vetor,q,r)
    intercala(vetor,p,q,r)
  return vetor

##  Selection Sort


In [4]:
def selectionSort(A):
  for j in range(0, len(A) - 1):
    menor = A[j]
    pos = j
    for i in range(j+1, len(A)):
      if(A[i] < menor):
        menor = A[i]
        pos = i
    
    A[pos] = A[j]
    A[j] = menor

  return A 

##  Bubble Sort


In [5]:
def bubbleSort(vetor):
  for i in range(0,len(vetor)):
    for j in range(0,len(vetor)-i-1):
      if vetor[j] > vetor[j+1]:
         (vetor[j], vetor[j+1]) = (vetor[j+1], vetor[j])
  
  return vetor

## Heap Sort

In [6]:
def arrumaHeap(vetor, tamanho, i):
    pai = i
    filhoEsq = 2 * i + 1
    filhoDir = 2 * i + 2
 
 
    if filhoEsq < tamanho and vetor[pai] < vetor[filhoEsq]:
        pai = filhoEsq
 
 
    if filhoDir < tamanho and vetor[pai] < vetor[filhoDir]:
        pai = filhoDir
 
 
    if pai != i:
        (vetor[i], vetor[pai]) = (vetor[pai], vetor[i])
        arrumaHeap(vetor, tamanho, pai)




def heapSort(vetor):
  tamanho = len(vetor)
  
  for i in range(tamanho // 2 - 1, -1, -1):
    arrumaHeap(vetor, tamanho, i)
  
  for i in range(tamanho - 1, 0, -1):
    (vetor[i], vetor[0]) = (vetor[0], vetor[i])
    arrumaHeap(vetor, i, 0)
  
  return vetor

## Quick Sort com pivo sendo o ultimo elemento do arranjo

> pivo = *A[A-comprimento]*

In [7]:
def partition(vetor,p,r):
  pivo = vetor[r]
  i = p-1
  for j in range(p,r):
    if vetor[j]<=pivo:
      i = i+1
      (vetor[i], vetor[j]) = (vetor[j], vetor[i])
  
  (vetor[i+1], vetor[r]) = (vetor[r], vetor[i+1])
  return i + 1




def quickSort(vetor,p=0,r=None):
  if r is None:
    r = len(vetor)-1
  if p < r:
    q = partition(vetor,p,r)
    quickSort(vetor,p,q-1)
    quickSort(vetor,q+1,r)
  
  return vetor

# Questões



1.   Escolha pelo menos 3 arranjos. Ex: ***A[5,...,1000,...,100]*** e mostre o funcionamento dos Algoritmos realizando a ordenação.





In [81]:
def testSort(array):
  print(f'initial array {array}')
  print('Insertion sort')
  print(insertionSort(np.copy(array)))

  print('Merge sort')
  print(mergeSort(np.copy(array)))

  print('Selection sort')
  print(selectionSort(np.copy(array)))

  print('Bubble sort')
  print(bubbleSort(np.copy(array)))

  print('Heap sort')
  print(heapSort(np.copy(array)))
  
  print('Quick sort')
  print(quickSort(np.copy(array)))

ARRAY1 = generateArray(10, 0, 1000)
ARRAY2 = generateArray(5, 0, 1000)
ARRAY3 = generateArray(7, 0, 1000)

testSort(ARRAY1)
print('\n')
testSort(ARRAY2)
print('\n')
testSort(ARRAY3)

initial array [785 313 359 353 571 231 713 653  14 313]
Insertion sort
[ 14 231 313 313 353 359 571 653 713 785]
Merge sort
[ 14 231 313 313 353 359 571 653 713 785]
Selection sort
[ 14 231 313 313 353 359 571 653 713 785]
Bubble sort
[ 14 231 313 313 353 359 571 653 713 785]
Heap sort
[ 14 231 313 313 353 359 571 653 713 785]
Quick sort
[ 14 231 313 313 353 359 571 653 713 785]


initial array [ 67 699 999  94 163]
Insertion sort
[ 67  94 163 699 999]
Merge sort
[ 67  94 163 699 999]
Selection sort
[ 67  94 163 699 999]
Bubble sort
[ 67  94 163 699 999]
Heap sort
[ 67  94 163 699 999]
Quick sort
[ 67  94 163 699 999]


initial array [235 798 547 540 786 359 946]
Insertion sort
[235 359 540 547 786 798 946]
Merge sort
[235 359 540 547 786 798 946]
Selection sort
[235 359 540 547 786 798 946]
Bubble sort
[235 359 540 547 786 798 946]
Heap sort
[235 359 540 547 786 798 946]
Quick sort
[235 359 540 547 786 798 946]
